DROP TABLE IF EXISTS IDN_THRIFT_SESSION;
CREATE TABLE IDN_AUTH_SESSION_STORE (
  SESSION_ID VARCHAR(100) DEFAULT NULL,
  SESSION_TYPE VARCHAR(100) DEFAULT NULL,
  SESSION_OBJECT BYTEA,
  TIME_CREATED TIMESTAMP,
  PRIMARY KEY (SESSION_ID, SESSION_TYPE)
);

UPDATE IDP_AUTHENTICATOR SET NAME='samlsso' WHERE NAME = 'saml2sso' AND TENANT_ID = '-1234';