ALTER TABLE IDN_SAML2_ASSERTION_STORE ADD COLUMN ASSERTION BLOB;

ALTER TABLE IDN_STS_STORE MODIFY COLUMN TOKEN_CONTENT BLOB(1024);

ALTER TABLE WF_BPS_PROFILE ADD CALLBACK_USERNAME VARCHAR(45);

ALTER TABLE WF_BPS_PROFILE ADD CALLBACK_PASSWORD VARCHAR(255);

ALTER TABLE IDN_SCIM_GROUP DROP INDEX IDX_IDN_SCIM_GROUP_TI_RN_AN;

CREATE INDEX IDX_IDN_SCIM_GROUP_TI_RN_AN ON IDN_SCIM_GROUP (TENANT_ID, ROLE_NAME, ATTR_NAME(500));

ALTER TABLE FIDO_DEVICE_STORE MODIFY DEVICE_DATA VARCHAR(2048);

ALTER TABLE IDN_OAUTH_CONSUMER_APPS MODIFY CALLBACK_URL VARCHAR(2048);

ALTER TABLE IDN_OAUTH1A_REQUEST_TOKEN MODIFY CALLBACK_URL VARCHAR(2048);

ALTER TABLE IDN_OAUTH2_AUTHORIZATION_CODE MODIFY CALLBACK_URL VARCHAR(2048);

CREATE INDEX IDX_USER_RID ON IDN_UMA_RESOURCE (RESOURCE_ID, RESOURCE_OWNER_NAME, USER_DOMAIN, CLIENT_ID);

