name: "🚀 Improvement Request"
description: Suggest an improvement to the product.
labels: ["Type/Improvement"]
body:
  - type: textarea
    id: limitation
    attributes:
      label: Current Limitation
      description: Describe the current limitation.
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: Describe the improvement you suggest.
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Please select the area issue is related to
      options:
        - Authentication & Registration
        - User & Identity Administration
        - API Access Mgt & Authorization
        - B2B
        - Identity Server Core
        - Other
      default: 6
      multiple: false
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Enter product/component version.
    validations:
      required: false
  - type: checkboxes
    id: developer-checklist
    attributes:
      label: Developer Checklist
      description: Please review and confirm the following items before closing the issue.
      options:
        - label: "[Behavioural Change] Does this change introduce a behavioral change to the product?"
        - label: " ↳ Approved by team lead"
        - label: " ↳ Label `impact/behavioral-change` added"
        - label: "[Migration Impact] Does this change have a migration impact?"
        - label: " ↳ Migration label added (e.g., `7.2.0-migration`)"
        - label: " ↳ Migration issues created and linked"
        - label: "[New Configuration] Does this change introduce a new configuration?"
        - label: " ↳ Configuration is properly documented"
