name: "💡 New Feature Request"
description: Suggest new functionality and features for the product.
labels: ["Type/NewFeature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What is the problem this feature will solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to have.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe any alternatives have you considered
    validations:
      required: false
  - type: dropdown
    id: area
    attributes:
      label: Please select the area issue is related to
      options:
        - Authentication & Registration
        - User & Identity Administration
        - API Access Mgt & Authorization
        - B2B
        - Identity Server Core
        - Other
      default: 5
      multiple: false
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Enter product/component version.
    validations:
      required: false
  - type: checkboxes
    id: developer-checklist
    attributes:
      label: Developer Checklist
      description: Please review and confirm the following items before closing the issue.
      options:
        - label: "[Behavioural Change] Does this change introduce a behavioral change to the product?"
        - label: " ↳ Approved by team lead"
        - label: " ↳ Label `impact/behavioral-change` added"
        - label: "[Migration Impact] Does this change have a migration impact?"
        - label: " ↳ Migration label added (e.g., `7.2.0-migration`)"
        - label: " ↳ Migration issues created and linked"
        - label: "[New Configuration] Does this change introduce a new configuration?"
        - label: " ↳ Label `config` added"
        - label: " ↳ Configuration is properly documented"
  - type: dropdown
    id: behavioral-change
    attributes:
      label: "Behavioural Change – Does this change introduce a behavioral change to the product?"
      options:
        - "Yes"
        - "No"

  - type: markdown
    attributes:
      value: |
          If yes
              - [ ] Approved by team lead
            - [ ] Label Added

  - type: dropdown
    id: migration-impact
    attributes:
      label: "Migration Impact – Does this change have a migration impact?"
      options:
        - "Yes"
        - "No"

  - type: dropdown
    id: new-configuration
    attributes:
      label: "New Configuration – Does this change introduce a new configuration?"
      options:
        - "Yes"
        - "No"
