name: "✍️ Create a Task"
description: Create a new task.
labels: ["Type/Task"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of what needs to be done.
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Please select the area issue is related to
      options:
        - "Authentication & Registration"
        - "User & Identity Administration"
        - "API Access Mgt & Authorization"
        - "B2B"
        - "Identity Server Core"
        - "Other"
      default: 5
      multiple: false
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Enter product/component version.
    validations:
      required: false

  - type: checkboxes
    id: developer-checklist
    attributes:
      label: Developer Checklist
      description: Please review and confirm the following items before closing the issue.
      options:
        - label: "[Behavioural Change] Does this change introduce a behavioral change to the product?"
        - label: " ↳ Approved by team lead"
        - label: " ↳ Label `impact/behavioral-change` added"
        - label: "[Migration Impact] Does this change have a migration impact?"
        - label: " ↳ Migration label added (e.g., `7.2.0-migration`)"
        - label: " ↳ Migration issues created and linked"
        - label: "[New Configuration] Does this change introduce a new configuration?"
        - label: " ↳ Label `config` added"
        - label: " ↳ Configuration is properly documented"

  - type: markdown
    attributes:
      value: |
        ### 🧪 Developer Review Checklist
        Please answer the following questions. If you answer **Yes**, make sure to provide the follow-up information in the next dropdown.

  - type: dropdown
    id: behavioral-change
    attributes:
      label: Behavioural Change
      description: Does this change introduce a behavioral change to the product?
      options:
        - "Yes"
        - "No"

  - type: dropdown
    id: behavioral-change-followup
    attributes:
      label: Behavioural Change Follow-up
      description: If **Yes**, is it approved by the team lead and labeled correctly?
      options:
        - "Approved by team lead & label `impact/behavioral-change` added"
        - "Only team lead approved"
        - "Only label added"
        - "Not applicable / No"

  - type: dropdown
    id: migration-impact
    attributes:
      label: Migration Impact
      description: Does this change have a migration impact?
      options:
        - "Yes"
        - "No"

  - type: dropdown
    id: migration-impact-followup
    attributes:
      label: Migration Impact Follow-up
      description: If **Yes**, confirm if label was added and migration issues were created.
      options:
        - "Label added and issues created & linked"
        - "Only label added"
        - "Only issues created"
        - "Not applicable / No"

  - type: dropdown
    id: new-configuration
    attributes:
      label: New Configuration
      description: Does this change introduce a new configuration?
      options:
        - "Yes"
        - "No"

  - type: dropdown
    id: new-configuration-followup
    attributes:
      label: New Configuration Follow-up
      description: If **Yes**, confirm the configuration is documented and labeled correctly.
      options:
        - "Configuration documented & label `config` added"
        - "Only label added"
        - "Only documented"
        - "Not applicable / No"

