name: Windows+jdk1.8

on:
  schedule:
    # Runs at 12AM LK time.
    - cron:  '30 18 * * *'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Allow longpaths
      run: git config --system core.longpaths true
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean install
